### 1. Pegar um usuario para usar o ID nos testes abaixo
GET http://localhost:3000/api/usuarios

### 2. Pegar um livro para usar o ID nos testes abaixo
GET http://localhost:3000/api/livros


### ---------- LIVROS ----------

### Inserir livro
POST http://localhost:3000/api/livros
Content-Type: application/json

{
  "isbn": "9788512345999",
  "titulo": "Livro Teste",
  "autor": "Autor Teste",
  "editora": "Novatec",
  "ano": 2024,
  "categoria": "Computação",
  "palavrasChave": ["teste"],
  "quantidade": 5
}

### Atualizar quantidade
PATCH http://localhost:3000/api/livros/6a370708ec387ea976abc178/quantidade
Content-Type: application/json

{
  "quantidade": 10
}

### Alterar categoria
PATCH http://localhost:3000/api/livros/6a370708ec387ea976abc178/categoria
Content-Type: application/json

{
  "categoria": "Banco de Dados"
}

### Remover livro
DELETE http://localhost:3000/api/livros/6a370708ec387ea976abc178


### ---------- USUARIOS ----------

### Bloquear usuario
PATCH http://localhost:3000/api/usuarios/6a370708ec387ea976abc114/bloquear

### Reativar usuario
PATCH http://localhost:3000/api/usuarios/6a370708ec387ea976abc114/reativar

### Alterar curso
PATCH http://localhost:3000/api/usuarios/6a370708ec387ea976abc114/curso
Content-Type: application/json

{
  "curso": "Engenharia de Software"
}


### ---------- EMPRESTIMOS ----------

### Realizar emprestimo
POST http://localhost:3000/api/emprestimos
Content-Type: application/json

{
  "usuario_id": "6a370708ec387ea976abc114",
  "livro_id": "6a370708ec387ea976abc18a"
}

### Listar emprestimos
GET http://localhost:3000/api/emprestimos

### Registrar devolucao 
PATCH http://localhost:3000/api/emprestimos/6a384835f203a68b4fc0882f/devolucao

### Renovar emprestimo
PATCH http://localhost:3000/api/emprestimos/6a3715318477f36f9ddca7ca/renovar



### Q1 - Livros Computação após 2020
GET http://localhost:3000/api/consultas/livros-por-categoria-ano

### Q2 - Usuarios cadastrados nos ultimos 30 dias
GET http://localhost:3000/api/consultas/usuarios-recentes

### Q3 - Emprestimos em atraso
GET http://localhost:3000/api/consultas/emprestimos-atrasados

### Q4 - Livros nunca emprestados
GET http://localhost:3000/api/consultas/livros-nunca-emprestados

### Q5 - Top 10 usuarios com mais emprestimos
GET http://localhost:3000/api/consultas/top-usuarios-emprestimos





### Q6 - Livros por categoria
GET http://localhost:3000/api/agregacoes/livros-por-categoria

### Q7 - Media de avaliacoes por livro
GET http://localhost:3000/api/agregacoes/media-avaliacoes-por-livro

### Q8 - Top 10 livros mais emprestados
GET http://localhost:3000/api/agregacoes/top10-livros-mais-emprestados

### Q9 - Cursos que mais utilizam a biblioteca
GET http://localhost:3000/api/agregacoes/cursos-que-mais-utilizam

### Q10 - Taxa de devolucao por mes
GET http://localhost:3000/api/agregacoes/taxa-devolucao-por-mes

### Q11 - Ranking de autores mais lidos
GET http://localhost:3000/api/agregacoes/ranking-autores-mais-lidos

### Q12 - Livros com nota media inferior a 3
GET http://localhost:3000/api/agregacoes/livros-nota-media-baixa






### Q13 - Emprestimos detalhados (usuario + livro + data)
GET http://localhost:3000/api/lookups/emprestimos-detalhados

### Q14 - Avaliacoes detalhadas (usuario + livro + nota + comentario)
GET http://localhost:3000/api/lookups/avaliacoes-detalhadas

### Q15 - Relatorio completo de um usuario
GET http://localhost:3000/api/lookups/relatorio-usuario/6a370708ec387ea976abc115






### Q16 - Busca por "mongodb"
GET http://localhost:3000/api/search/livros?termo=mongodb

### Q17 - Busca fuzzy por "algoritmo"
GET http://localhost:3000/api/search/livros-similares?termo=algoritmo

### Q18 - Autocomplete de titulo
GET http://localhost:3000/api/search/autocomplete-titulo?termo=Liv